exit:0
#Wed Sep 30 03:50:15 GMT+08:00 2026
grade@1.tint=-0.3
grade@1.exposure=-0.2
grain@3.amount=8.23
lut=ET-64.cube
grain@3.size=2.0
grade@2.alpha=1.0
grade@2.temp=0.0
grade@2.low=1.0
lut@1.enable=1.0
grade@1.mid=0.0
grade@1.high=0.0
lut@1.on=1.0
grade@2.tint=0.0
grade@1.saturation=0.0
grade@1.contrast=0.0
grade@1.temp=-0.6
grade@2.mid=1.0
grade@1.low=1.0
lut@1.alpha=1.0
vig@2.r=0.03
chain=lut\:1,vig\:2,grain\:3,grade\:1,grade\:2
vig@2.start=0.22
vig@2.end=0.737
grade@1.alpha=1.0
vig@2.g=0.0
grain@3.mono=1.0
vig@2.alpha=1.0
vig@2.amount=0.161
vig@2.enable=1.0
grain@3.alpha=1.0
vig@2.b=0.14
grain@3.enable=1.0
grade@1.enable=1.0
grade@2.enable=1.0
grade@2.high=1.0
grade@2.saturation=0.0
grade@2.exposure=0.0
grade@2.contrast=-0.1
